USE [master]
GO
/****** Object:  Database [Notes]    Script Date: 22.05.2018 21:18:59 ******/
CREATE DATABASE [Notes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Notes', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Notes.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Notes_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Notes_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Notes] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Notes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Notes] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Notes] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Notes] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Notes] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Notes] SET ARITHABORT OFF 
GO
ALTER DATABASE [Notes] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Notes] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Notes] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Notes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Notes] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Notes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Notes] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Notes] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Notes] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Notes] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Notes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Notes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Notes] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Notes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Notes] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Notes] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Notes] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Notes] SET RECOVERY FULL 
GO
ALTER DATABASE [Notes] SET  MULTI_USER 
GO
ALTER DATABASE [Notes] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Notes] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Notes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Notes] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Notes] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Notes', N'ON'
GO
ALTER DATABASE [Notes] SET QUERY_STORE = OFF
GO
USE [Notes]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [Notes]
GO
/****** Object:  Table [dbo].[Note]    Script Date: 22.05.2018 21:19:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Note](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[NoteText] [nvarchar](2000) NULL,
 CONSTRAINT [PK_Note] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 22.05.2018 21:19:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Username] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](500) NOT NULL,
	[Role] [nvarchar](50) NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Notes] SET  READ_WRITE 
GO
